services:
  - type: web
    name: hackheritage-timetable-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/Pushpen2005/hackheritage-timetable
    branch: main
    rootDir: server
    envVars:
      - key: MONGO_URI
        value: <your-mongodb-uri>
      - key: PORT
        value: 5000
